#!/bin/bash

for row in 256 512 1024; do

	for column in 256 512 1024; do

                for TEST in 1 2; do

                	for NODES in 4 8 12; do

                                                mpiexec -n $NODES python -m matrixmul_rect.py $row $column $column $row >> mat_mul.$row.$column.txt

			done
		done
	done
done
